"""
create_static_files.py
======================
Cricklytics — Static JSON Generator (Source D)
Creates the three static metadata files that no API provides.
These files are created once and edited manually as needed.

Run this ONCE:
    python create_static_files.py

Output:
    data/static/players_meta.json   — DOB, birthplace, cap numbers, photo URLs
    data/static/teams_meta.json     — board name, founded, WC titles, confederation
    data/static/venues_meta.json    — capacity, pitch type, dew factor etc.
"""

import json
import os

BASE_DIR    = os.path.dirname(os.path.abspath(__file__))
STATIC_DIR  = os.path.join(BASE_DIR, "data", "static")
os.makedirs(STATIC_DIR, exist_ok=True)


# ════════════════════════════════════════════════════════════════════════════
# PLAYERS META
# ════════════════════════════════════════════════════════════════════════════
# Keys match the Cricsheet player registry names exactly.
# image_url: filled in by fetch_live.py --photos (leave empty for now)
# iso_code: used by frontend to load flag SVG from jsDelivr CDN

PLAYERS_META = {
    "V Kohli": {
        "full_name":    "Virat Kohli",
        "dob":          "1988-11-05",
        "age":          36,
        "birthplace":   "Delhi, India",
        "nationality":  "Indian",
        "country":      "India",
        "iso_code":     "IN",
        "batting_style": "Right-hand bat",
        "bowling_style": "Right-arm medium",
        "role":         "Batsman",
        "ipl_team":     "Royal Challengers Bengaluru",
        "debut_test":   "2011-06-20",
        "debut_odi":    "2008-08-18",
        "debut_t20i":   "2010-06-12",
        "cap_india":    253,
        "image_url":    "",
        "status":       "active",
    },
    "RG Sharma": {
        "full_name":    "Rohit Gurunath Sharma",
        "dob":          "1987-04-30",
        "age":          37,
        "birthplace":   "Nagpur, India",
        "nationality":  "Indian",
        "country":      "India",
        "iso_code":     "IN",
        "batting_style": "Right-hand bat",
        "bowling_style": "Right-arm off-break",
        "role":         "Batsman",
        "ipl_team":     "Mumbai Indians",
        "debut_test":   "2013-11-06",
        "debut_odi":    "2007-06-23",
        "debut_t20i":   "2007-09-19",
        "cap_india":    230,
        "image_url":    "",
        "status":       "active",
    },
    "JJ Bumrah": {
        "full_name":    "Jasprit Jasbirsingh Bumrah",
        "dob":          "1993-12-06",
        "age":          31,
        "birthplace":   "Ahmedabad, India",
        "nationality":  "Indian",
        "country":      "India",
        "iso_code":     "IN",
        "batting_style": "Right-hand bat",
        "bowling_style": "Right-arm fast",
        "role":         "Bowler",
        "ipl_team":     "Mumbai Indians",
        "debut_test":   "2018-01-05",
        "debut_odi":    "2016-01-23",
        "debut_t20i":   "2016-01-26",
        "cap_india":    289,
        "image_url":    "",
        "status":       "active",
    },
    "HH Pandya": {
        "full_name":    "Hardik Himanshu Pandya",
        "dob":          "1993-10-11",
        "age":          31,
        "birthplace":   "Surat, India",
        "nationality":  "Indian",
        "country":      "India",
        "iso_code":     "IN",
        "batting_style": "Right-hand bat",
        "bowling_style": "Right-arm fast-medium",
        "role":         "All-Rounder",
        "ipl_team":     "Mumbai Indians",
        "debut_test":   "2018-01-05",
        "debut_odi":    "2016-10-16",
        "debut_t20i":   "2016-01-26",
        "cap_india":    287,
        "image_url":    "",
        "status":       "active",
    },
    "RA Jadeja": {
        "full_name":    "Ravindrasinh Anirudhsinh Jadeja",
        "dob":          "1988-12-06",
        "age":          36,
        "birthplace":   "Navagam-Khed, India",
        "nationality":  "Indian",
        "country":      "India",
        "iso_code":     "IN",
        "batting_style": "Left-hand bat",
        "bowling_style": "Slow left-arm orthodox",
        "role":         "All-Rounder",
        "ipl_team":     "Chennai Super Kings",
        "debut_test":   "2012-12-13",
        "debut_odi":    "2009-02-08",
        "debut_t20i":   "2009-02-10",
        "cap_india":    268,
        "image_url":    "",
        "status":       "active",
    },
    "KL Rahul": {
        "full_name":    "Kannaur Lokesh Rahul",
        "dob":          "1992-04-18",
        "age":          32,
        "birthplace":   "Mangaluru, India",
        "nationality":  "Indian",
        "country":      "India",
        "iso_code":     "IN",
        "batting_style": "Right-hand bat",
        "bowling_style": "Right-arm off-break",
        "role":         "Wicket-Keeper Batsman",
        "ipl_team":     "Lucknow Super Giants",
        "debut_test":   "2014-12-26",
        "debut_odi":    "2016-06-11",
        "debut_t20i":   "2015-07-07",
        "cap_india":    282,
        "image_url":    "",
        "status":       "active",
    },
    "SPD Smith": {
        "full_name":    "Steven Peter Devereux Smith",
        "dob":          "1989-06-02",
        "age":          35,
        "birthplace":   "Sydney, Australia",
        "nationality":  "Australian",
        "country":      "Australia",
        "iso_code":     "AU",
        "batting_style": "Right-hand bat",
        "bowling_style": "Right-arm leg-break",
        "role":         "Batsman",
        "ipl_team":     "Rajasthan Royals",
        "debut_test":   "2010-07-15",
        "debut_odi":    "2010-02-24",
        "debut_t20i":   "2010-02-26",
        "cap_australia": None,
        "image_url":    "",
        "status":       "active",
    },
    "PJ Cummins": {
        "full_name":    "Patrick James Cummins",
        "dob":          "1993-05-08",
        "age":          31,
        "birthplace":   "Westmead, Australia",
        "nationality":  "Australian",
        "country":      "Australia",
        "iso_code":     "AU",
        "batting_style": "Right-hand bat",
        "bowling_style": "Right-arm fast",
        "role":         "Bowler",
        "ipl_team":     "Kolkata Knight Riders",
        "debut_test":   "2011-11-15",
        "debut_odi":    "2012-09-21",
        "debut_t20i":   "2011-02-05",
        "image_url":    "",
        "status":       "active",
    },
    "JE Root": {
        "full_name":    "Joseph Edward Root",
        "dob":          "1990-12-30",
        "age":          34,
        "birthplace":   "Sheffield, England",
        "nationality":  "English",
        "country":      "England",
        "iso_code":     "ENGLAND",
        "batting_style": "Right-hand bat",
        "bowling_style": "Right-arm off-break",
        "role":         "Batsman",
        "ipl_team":     None,
        "debut_test":   "2012-12-13",
        "debut_odi":    "2013-01-11",
        "debut_t20i":   "2012-03-31",
        "image_url":    "",
        "status":       "active",
    },
    "BA Stokes": {
        "full_name":    "Benjamin Andrew Stokes",
        "dob":          "1991-06-04",
        "age":          33,
        "birthplace":   "Christchurch, New Zealand",
        "nationality":  "English",
        "country":      "England",
        "iso_code":     "ENGLAND",
        "batting_style": "Left-hand bat",
        "bowling_style": "Right-arm fast-medium",
        "role":         "All-Rounder",
        "ipl_team":     None,
        "debut_test":   "2013-12-13",
        "debut_odi":    "2011-08-24",
        "debut_t20i":   "2011-08-31",
        "image_url":    "",
        "status":       "active",
    },
    "Babar Azam": {
        "full_name":    "Babar Azam",
        "dob":          "1994-10-15",
        "age":          30,
        "birthplace":   "Lahore, Pakistan",
        "nationality":  "Pakistani",
        "country":      "Pakistan",
        "iso_code":     "PK",
        "batting_style": "Right-hand bat",
        "bowling_style": "Right-arm medium",
        "role":         "Batsman",
        "ipl_team":     None,
        "debut_test":   "2017-10-13",
        "debut_odi":    "2015-05-31",
        "debut_t20i":   "2016-05-27",
        "image_url":    "",
        "status":       "active",
    },
    "Shaheen Shah Afridi": {
        "full_name":    "Shaheen Shah Afridi",
        "dob":          "2000-04-06",
        "age":          24,
        "birthplace":   "Khyber Agency, Pakistan",
        "nationality":  "Pakistani",
        "country":      "Pakistan",
        "iso_code":     "PK",
        "batting_style": "Right-hand bat",
        "bowling_style": "Left-arm fast",
        "role":         "Bowler",
        "ipl_team":     None,
        "debut_test":   "2018-12-11",
        "debut_odi":    "2018-11-18",
        "debut_t20i":   "2018-11-03",
        "image_url":    "",
        "status":       "active",
    },
    "KS Williamson": {
        "full_name":    "Kane Stuart Williamson",
        "dob":          "1990-08-08",
        "age":          34,
        "birthplace":   "Tauranga, New Zealand",
        "nationality":  "New Zealander",
        "country":      "New Zealand",
        "iso_code":     "NZ",
        "batting_style": "Right-hand bat",
        "bowling_style": "Right-arm off-break",
        "role":         "Batsman",
        "ipl_team":     "Sunrisers Hyderabad",
        "debut_test":   "2010-01-02",
        "debut_odi":    "2010-08-01",
        "debut_t20i":   "2008-12-26",
        "image_url":    "",
        "status":       "active",
    },
    "K Rabada": {
        "full_name":    "Kagiso Rabada",
        "dob":          "1995-05-25",
        "age":          29,
        "birthplace":   "Johannesburg, South Africa",
        "nationality":  "South African",
        "country":      "South Africa",
        "iso_code":     "ZA",
        "batting_style": "Right-hand bat",
        "bowling_style": "Right-arm fast",
        "role":         "Bowler",
        "ipl_team":     "Punjab Kings",
        "debut_test":   "2015-12-28",
        "debut_odi":    "2014-10-25",
        "debut_t20i":   "2014-11-20",
        "image_url":    "",
        "status":       "active",
    },
    "Rashid Khan": {
        "full_name":    "Rashid Khan Arman",
        "dob":          "1998-09-20",
        "age":          26,
        "birthplace":   "Nangarhar, Afghanistan",
        "nationality":  "Afghan",
        "country":      "Afghanistan",
        "iso_code":     "AF",
        "batting_style": "Left-hand bat",
        "bowling_style": "Right-arm leg-break",
        "role":         "Bowler",
        "ipl_team":     "Gujarat Titans",
        "debut_test":   "2018-06-14",
        "debut_odi":    "2015-10-11",
        "debut_t20i":   "2015-10-09",
        "image_url":    "",
        "status":       "active",
    },
    "Shakib Al Hasan": {
        "full_name":    "Shakib Al Hasan",
        "dob":          "1987-03-24",
        "age":          37,
        "birthplace":   "Magura, Bangladesh",
        "nationality":  "Bangladeshi",
        "country":      "Bangladesh",
        "iso_code":     "BD",
        "batting_style": "Left-hand bat",
        "bowling_style": "Slow left-arm orthodox",
        "role":         "All-Rounder",
        "ipl_team":     None,
        "debut_test":   "2007-05-25",
        "debut_odi":    "2006-08-06",
        "debut_t20i":   "2006-11-28",
        "image_url":    "",
        "status":       "active",
    },
}


# ════════════════════════════════════════════════════════════════════════════
# TEAMS META
# ════════════════════════════════════════════════════════════════════════════

TEAMS_META = {
    "India": {
        "full_name":      "India",
        "code":           "IND",
        "iso_code":       "IN",
        "board":          "Board of Control for Cricket in India (BCCI)",
        "founded":        1928,
        "confederation":  "Asia",
        "home_ground":    "Narendra Modi Stadium, Ahmedabad",
        "formats":        ["Test", "ODI", "T20I"],
        "icc_member":     "Full Member",
        "status":         "active",
        "wc_titles": {
            "ODI World Cup":  [1983, 2011],
            "T20 World Cup":  [2007, 2024],
            "Champions Trophy": [2002, 2013],
            "WTC":            [],
        },
        "icc_trophies":   4,
    },
    "Australia": {
        "full_name":      "Australia",
        "code":           "AUS",
        "iso_code":       "AU",
        "board":          "Cricket Australia (CA)",
        "founded":        1905,
        "confederation":  "Pacific",
        "home_ground":    "Melbourne Cricket Ground",
        "formats":        ["Test", "ODI", "T20I"],
        "icc_member":     "Full Member",
        "status":         "active",
        "wc_titles": {
            "ODI World Cup":  [1987, 1999, 2003, 2007, 2015, 2023],
            "T20 World Cup":  [2021],
            "Champions Trophy": [2006, 2009],
            "WTC":            [2021, 2023],
        },
        "icc_trophies":   9,
    },
    "England": {
        "full_name":      "England",
        "code":           "ENG",
        "iso_code":       "ENGLAND",
        "board":          "England and Wales Cricket Board (ECB)",
        "founded":        1877,
        "confederation":  "Europe",
        "home_ground":    "Lord's Cricket Ground, London",
        "formats":        ["Test", "ODI", "T20I"],
        "icc_member":     "Full Member",
        "status":         "active",
        "wc_titles": {
            "ODI World Cup":  [2019],
            "T20 World Cup":  [2010, 2022],
            "Champions Trophy": [2004],
            "WTC":            [],
        },
        "icc_trophies":   4,
    },
    "Pakistan": {
        "full_name":      "Pakistan",
        "code":           "PAK",
        "iso_code":       "PK",
        "board":          "Pakistan Cricket Board (PCB)",
        "founded":        1948,
        "confederation":  "Asia",
        "home_ground":    "Gaddafi Stadium, Lahore",
        "formats":        ["Test", "ODI", "T20I"],
        "icc_member":     "Full Member",
        "status":         "active",
        "wc_titles": {
            "ODI World Cup":  [1992],
            "T20 World Cup":  [2009],
            "Champions Trophy": [2017],
            "WTC":            [],
        },
        "icc_trophies":   3,
    },
    "South Africa": {
        "full_name":      "South Africa",
        "code":           "SA",
        "iso_code":       "ZA",
        "board":          "Cricket South Africa (CSA)",
        "founded":        1909,
        "confederation":  "Africa",
        "home_ground":    "Newlands Cricket Ground, Cape Town",
        "formats":        ["Test", "ODI", "T20I"],
        "icc_member":     "Full Member",
        "status":         "active",
        "wc_titles": {
            "ODI World Cup":  [],
            "T20 World Cup":  [],
            "Champions Trophy": [],
            "WTC":            [],
        },
        "icc_trophies":   0,
    },
    "New Zealand": {
        "full_name":      "New Zealand",
        "code":           "NZ",
        "iso_code":       "NZ",
        "board":          "New Zealand Cricket (NZC)",
        "founded":        1894,
        "confederation":  "Pacific",
        "home_ground":    "Eden Park, Auckland",
        "formats":        ["Test", "ODI", "T20I"],
        "icc_member":     "Full Member",
        "status":         "active",
        "wc_titles": {
            "ODI World Cup":  [],
            "T20 World Cup":  [],
            "Champions Trophy": [],
            "WTC":            [2021],
        },
        "icc_trophies":   1,
    },
    "West Indies": {
        "full_name":      "West Indies",
        "code":           "WI",
        "iso_code":       "WI",
        "board":          "Cricket West Indies (CWI)",
        "founded":        1928,
        "confederation":  "Americas",
        "home_ground":    "Kensington Oval, Barbados",
        "formats":        ["Test", "ODI", "T20I"],
        "icc_member":     "Full Member",
        "status":         "active",
        "wc_titles": {
            "ODI World Cup":  [1975, 1979],
            "T20 World Cup":  [2012, 2016],
            "Champions Trophy": [],
            "WTC":            [],
        },
        "icc_trophies":   4,
    },
    "Sri Lanka": {
        "full_name":      "Sri Lanka",
        "code":           "SL",
        "iso_code":       "LK",
        "board":          "Sri Lanka Cricket (SLC)",
        "founded":        1922,
        "confederation":  "Asia",
        "home_ground":    "R. Premadasa Stadium, Colombo",
        "formats":        ["Test", "ODI", "T20I"],
        "icc_member":     "Full Member",
        "status":         "active",
        "wc_titles": {
            "ODI World Cup":  [1996],
            "T20 World Cup":  [2014],
            "Champions Trophy": [],
            "WTC":            [],
        },
        "icc_trophies":   2,
    },
    "Bangladesh": {
        "full_name":      "Bangladesh",
        "code":           "BAN",
        "iso_code":       "BD",
        "board":          "Bangladesh Cricket Board (BCB)",
        "founded":        1972,
        "confederation":  "Asia",
        "home_ground":    "Sher-e-Bangla National Cricket Stadium, Dhaka",
        "formats":        ["Test", "ODI", "T20I"],
        "icc_member":     "Full Member",
        "status":         "active",
        "wc_titles": {
            "ODI World Cup":  [],
            "T20 World Cup":  [],
            "Champions Trophy": [],
            "WTC":            [],
        },
        "icc_trophies":   0,
    },
    "Afghanistan": {
        "full_name":      "Afghanistan",
        "code":           "AFG",
        "iso_code":       "AF",
        "board":          "Afghanistan Cricket Board (ACB)",
        "founded":        2001,
        "confederation":  "Asia",
        "home_ground":    "Sharjah Cricket Stadium",
        "formats":        ["Test", "ODI", "T20I"],
        "icc_member":     "Full Member",
        "status":         "active",
        "wc_titles": {
            "ODI World Cup":  [],
            "T20 World Cup":  [],
            "Champions Trophy": [],
            "WTC":            [],
        },
        "icc_trophies":   0,
    },
    "Zimbabwe": {
        "full_name":      "Zimbabwe",
        "code":           "ZIM",
        "iso_code":       "ZW",
        "board":          "Zimbabwe Cricket (ZC)",
        "founded":        1992,
        "confederation":  "Africa",
        "home_ground":    "Harare Sports Club",
        "formats":        ["Test", "ODI", "T20I"],
        "icc_member":     "Full Member",
        "status":         "active",
        "wc_titles":      {},
        "icc_trophies":   0,
    },
    "Ireland": {
        "full_name":      "Ireland",
        "code":           "IRE",
        "iso_code":       "IE",
        "board":          "Cricket Ireland",
        "founded":        1923,
        "confederation":  "Europe",
        "home_ground":    "Malahide Cricket Club Ground, Dublin",
        "formats":        ["Test", "ODI", "T20I"],
        "icc_member":     "Full Member",
        "status":         "active",
        "wc_titles":      {},
        "icc_trophies":   0,
    },
}


# ════════════════════════════════════════════════════════════════════════════
# VENUES META
# ════════════════════════════════════════════════════════════════════════════

VENUES_META = {
    "Wankhede Stadium": {
        "full_name":      "Wankhede Stadium",
        "city":           "Mumbai",
        "country":        "India",
        "iso_code":       "IN",
        "capacity":       66000,
        "established":    1975,
        "managed_by":     "Mumbai Cricket Association (MCA)",
        "ends":           ["North Stand End", "South Stand End"],
        "floodlights":    True,
        "notable_events": ["2011 ICC World Cup Final", "IPL Finals"],
        "pitch": {
            "surface":    "Red soil · Flat",
            "pace_factor": "Medium-high",
            "spin_factor": "Low (early) → Medium (late)",
            "dew_factor":  "High (D/N matches)",
            "bounce":      "True and even",
            "best_toss":   "Field first (D/N)",
            "batting_friendly_pct": 72,
        },
    },
    "Narendra Modi Stadium": {
        "full_name":      "Narendra Modi Stadium",
        "city":           "Ahmedabad",
        "country":        "India",
        "iso_code":       "IN",
        "capacity":       110000,
        "established":    1982,
        "managed_by":     "Gujarat Cricket Association (GCA)",
        "ends":           ["Adani End", "BCCI End"],
        "floodlights":    True,
        "notable_events": ["2023 ODI World Cup Final", "IPL Finals"],
        "pitch": {
            "surface":    "Black soil · Flat",
            "pace_factor": "Medium",
            "spin_factor": "Medium → High (later)",
            "dew_factor":  "High (D/N)",
            "bounce":      "Low and even",
            "best_toss":   "Field first",
            "batting_friendly_pct": 75,
        },
    },
    "Eden Gardens": {
        "full_name":      "Eden Gardens",
        "city":           "Kolkata",
        "country":        "India",
        "iso_code":       "IN",
        "capacity":       68000,
        "established":    1864,
        "managed_by":     "Cricket Association of Bengal (CAB)",
        "ends":           ["High Court End", "Football Stand End"],
        "floodlights":    True,
        "notable_events": ["1987 World Cup Final", "2001 Historic Test vs Australia"],
        "pitch": {
            "surface":    "Black cotton soil · Spin-friendly",
            "pace_factor": "Low",
            "spin_factor": "High",
            "dew_factor":  "Medium",
            "bounce":      "Low",
            "best_toss":   "Bat first",
            "batting_friendly_pct": 45,
        },
    },
    "M. Chinnaswamy Stadium": {
        "full_name":      "M. Chinnaswamy Stadium",
        "city":           "Bengaluru",
        "country":        "India",
        "iso_code":       "IN",
        "capacity":       55000,
        "established":    1969,
        "managed_by":     "Karnataka State Cricket Association (KSCA)",
        "ends":           ["BEML End", "Pavilion End"],
        "floodlights":    True,
        "notable_events": ["IPL home ground of RCB"],
        "pitch": {
            "surface":    "Red soil · Balanced",
            "pace_factor": "Medium",
            "spin_factor": "Medium",
            "dew_factor":  "Low",
            "bounce":      "True",
            "best_toss":   "Bat first",
            "batting_friendly_pct": 65,
        },
    },
    "Melbourne Cricket Ground": {
        "full_name":      "Melbourne Cricket Ground",
        "city":           "Melbourne",
        "country":        "Australia",
        "iso_code":       "AU",
        "capacity":       100024,
        "established":    1853,
        "managed_by":     "Melbourne Cricket Club (MCC)",
        "ends":           ["Members End", "Great Southern Stand End"],
        "floodlights":    True,
        "notable_events": ["1992 World Cup Final", "Boxing Day Test (annual)"],
        "pitch": {
            "surface":    "Drop-in · Pace-friendly",
            "pace_factor": "High",
            "spin_factor": "Low",
            "dew_factor":  "Low",
            "bounce":      "Good and even",
            "best_toss":   "Bat first (day) / Field first (D/N)",
            "batting_friendly_pct": 40,
        },
    },
    "Sydney Cricket Ground": {
        "full_name":      "Sydney Cricket Ground",
        "city":           "Sydney",
        "country":        "Australia",
        "iso_code":       "AU",
        "capacity":       53500,
        "established":    1848,
        "managed_by":     "Sydney Cricket and Sports Ground Trust",
        "ends":           ["Randwick End", "Paddington End"],
        "floodlights":    True,
        "notable_events": ["New Year's Test (annual)"],
        "pitch": {
            "surface":    "Flat · High-scoring",
            "pace_factor": "Medium",
            "spin_factor": "High (later days)",
            "dew_factor":  "Low",
            "bounce":      "Variable",
            "best_toss":   "Bat first",
            "batting_friendly_pct": 60,
        },
    },
    "Lord's Cricket Ground": {
        "full_name":      "Lord's Cricket Ground",
        "city":           "London",
        "country":        "England",
        "iso_code":       "ENGLAND",
        "capacity":       30000,
        "established":    1814,
        "managed_by":     "Marylebone Cricket Club (MCC)",
        "ends":           ["Pavilion End", "Nursery End"],
        "floodlights":    False,
        "notable_events": ["Home of Cricket", "Multiple World Cup Finals"],
        "pitch": {
            "surface":    "Seam-friendly · Variable",
            "pace_factor": "High",
            "spin_factor": "Low",
            "dew_factor":  "Low",
            "bounce":      "Variable (slope)",
            "best_toss":   "Field first",
            "batting_friendly_pct": 42,
        },
    },
    "The Oval": {
        "full_name":      "Kia Oval (The Oval)",
        "city":           "London",
        "country":        "England",
        "iso_code":       "ENGLAND",
        "capacity":       25500,
        "established":    1845,
        "managed_by":     "Surrey County Cricket Club",
        "ends":           ["Pavilion End", "Vauxhall End"],
        "floodlights":    True,
        "notable_events": ["First ever Test match in England (1880)"],
        "pitch": {
            "surface":    "Flat · High-scoring",
            "pace_factor": "Medium",
            "spin_factor": "Medium (later)",
            "dew_factor":  "Low",
            "bounce":      "True",
            "best_toss":   "Bat first",
            "batting_friendly_pct": 62,
        },
    },
    "National Stadium": {
        "full_name":      "National Stadium",
        "city":           "Karachi",
        "country":        "Pakistan",
        "iso_code":       "PK",
        "capacity":       34228,
        "established":    1955,
        "managed_by":     "Pakistan Cricket Board (PCB)",
        "ends":           ["Karachi End", "City End"],
        "floodlights":    True,
        "notable_events": ["Pakistan's home fortress"],
        "pitch": {
            "surface":    "Flat · Spin later",
            "pace_factor": "Low",
            "spin_factor": "High (Day 3+)",
            "dew_factor":  "Medium",
            "bounce":      "Low",
            "best_toss":   "Bat first",
            "batting_friendly_pct": 58,
        },
    },
    "Gaddafi Stadium": {
        "full_name":      "Gaddafi Stadium",
        "city":           "Lahore",
        "country":        "Pakistan",
        "iso_code":       "PK",
        "capacity":       27000,
        "established":    1959,
        "managed_by":     "Pakistan Cricket Board (PCB)",
        "ends":           ["City End", "Gymnasium End"],
        "floodlights":    True,
        "notable_events": ["1996 World Cup Semi-final"],
        "pitch": {
            "surface":    "Flat · High-scoring",
            "pace_factor": "Low",
            "spin_factor": "Medium → High",
            "dew_factor":  "High (D/N)",
            "bounce":      "Low",
            "best_toss":   "Field first (D/N)",
            "batting_friendly_pct": 66,
        },
    },
    "Newlands Cricket Ground": {
        "full_name":      "Newlands Cricket Ground",
        "city":           "Cape Town",
        "country":        "South Africa",
        "iso_code":       "ZA",
        "capacity":       25000,
        "established":    1888,
        "managed_by":     "Western Province Cricket Association",
        "ends":           ["Wynberg End", "Pavilion End"],
        "floodlights":    True,
        "notable_events": ["Picturesque Table Mountain backdrop"],
        "pitch": {
            "surface":    "Balanced · Seam",
            "pace_factor": "High",
            "spin_factor": "Low",
            "dew_factor":  "Low",
            "bounce":      "Good",
            "best_toss":   "Field first",
            "batting_friendly_pct": 46,
        },
    },
}


# ════════════════════════════════════════════════════════════════════════════
# SAVE FILES
# ════════════════════════════════════════════════════════════════════════════

def save_static(filename, data):
    path = os.path.join(STATIC_DIR, filename)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    size_kb = os.path.getsize(path) / 1024
    print(f"  ✓  {filename:<30} {size_kb:>7.1f} KB  ({len(data)} entries)")


if __name__ == "__main__":
    print("=" * 55)
    print("  Cricklytics — Static JSON Generator")
    print("=" * 55)
    print(f"  Output: {STATIC_DIR}")
    print()

    save_static("players_meta.json", PLAYERS_META)
    save_static("teams_meta.json",   TEAMS_META)
    save_static("venues_meta.json",  VENUES_META)

    print()
    print("  Done. Edit these files manually to:")
    print("  • Add more players (follow the same structure)")
    print("  • Fill in image_url fields after running:")
    print("    python fetch_live.py --photos")
    print("=" * 55)
